<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite skipped="0" hostname="QTLSYS1-182" name="tests.QCStore" tests="4" failures="0" timestamp="08 May 2019 10:08:29 GMT" time="1786.368" errors="0">
  <testcase name="JQC_TLP_GraceDays_Deposit_dropdown_Txn" time="357.246" classname="tests.QCStore"/>
  <testcase name="JQC_TLP_Deceased_Txn" time="311.712" classname="tests.QCStore"/>
  <testcase name="JQC_DefaultPayment_Txn_Testdata" time="475.697" classname="tests.QCStore"/>
  <testcase name="JQC_DefaultPayment_Void_Txn_Testdata" time="641.713" classname="tests.QCStore"/>
=======
<testsuite skipped="0" hostname="QTLSYS2-238" name="tests.QCStore" tests="12" failures="2" timestamp="08 May 2019 11:31:19 GMT" time="4585.010" errors="0">
  <testcase name="QC_TLP_NewLoan_Txn" time="183.421" classname="tests.QCStore">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.QCCSRNewLoan.newLoan(QCCSRNewLoan.java:270)
at tests.QCStore.QC_TLP_NewLoan_Txn(QCStore.java:138)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- QC_TLP_NewLoan_Txn -->
  <testcase name="QC_NewLoan_Promotion_Txn" time="460.154" classname="tests.QCStore"/>
  <testcase name="QC_NewLoan_Void_Txn" time="131.302" classname="tests.QCStore">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.QCCSRNewLoan.newLoan(QCCSRNewLoan.java:270)
at tests.QCStore.QC_NewLoan_Void_Txn(QCStore.java:242)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- QC_NewLoan_Void_Txn -->
  <testcase name="QC_AgeStore_Void_Txn" time="583.380" classname="tests.QCStore"/>
  <testcase name="QC_TLP_Buyback_Txn" time="316.914" classname="tests.QCStore"/>
  <testcase name="QC_TLP_Buyback_Void_Txn" time="361.182" classname="tests.QCStore"/>
  <testcase name="QC_Installmentpayment_Txn" time="309.087" classname="tests.QCStore"/>
  <testcase name="QC_Installmentpayment_Void_Txn" time="362.952" classname="tests.QCStore"/>
  <testcase name="QC_PayAnyotherAmount_Txn" time="310.282" classname="tests.QCStore"/>
  <testcase name="QC_PayAnyotherAmount_Void_Txn" time="359.056" classname="tests.QCStore"/>
  <testcase name="QC_TLP_Writeoff_Recovery_Txn" time="545.655" classname="tests.QCStore"/>
  <testcase name="QC_TLP_Writeoff_Recovery_Void_Txn" time="661.625" classname="tests.QCStore"/>
>>>>>>> brahmith1.1
</testsuite> <!-- tests.QCStore -->
