<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="QTLSYS2-238" name="tests.QCStore" tests="8" failures="1" timestamp="08 Apr 2019 04:37:50 GMT" time="833.716" errors="0">
  <testcase name="QC_GraceDays_EODDeposit_Txn" time="506.734" classname="tests.QCStore"/>
  <testcase name="QC_FutureDeposit_EOD_Txn" time="326.982" classname="tests.QCStore">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.QCBorrowerRegistration.borrowerRegistration(QCBorrowerRegistration.java:519)
at tests.QCStore.QC_FutureDeposit_EOD_Txn(QCStore.java:1706)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- QC_FutureDeposit_EOD_Txn -->
  <testcase name="JQC_AgeStore_GraceDays_DCDeposit_Menu_Txn" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- JQC_AgeStore_GraceDays_DCDeposit_Menu_Txn -->
  <testcase name="JQC_ACH_PartialWORecovery_FullWORecovery_Void_Txn_Testdata" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- JQC_ACH_PartialWORecovery_FullWORecovery_Void_Txn_Testdata -->
  <testcase name="JQC_AgeStore_GraceDays_DCDeposit_Dropdown_Txn" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- JQC_AgeStore_GraceDays_DCDeposit_Dropdown_Txn -->
  <testcase name="JQC_AgeStore_DCDeposit_Txn" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- JQC_AgeStore_DCDeposit_Txn -->
  <testcase name="JQC_NewLoan_Veritec_Txn" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- JQC_NewLoan_Veritec_Txn -->
  <testcase name="JQC_AgeStore_DCDeposit_Menu_Txn" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- JQC_AgeStore_DCDeposit_Menu_Txn -->
</testsuite> <!-- tests.QCStore -->
