<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<<<<<<< HEAD
<testsuite skipped="0" hostname="QTLSYS2-48" name="tests.QCStore" tests="7" failures="0" timestamp="05 Mar 2019 15:44:14 GMT" time="7809.500" errors="1">
  <testcase name="EODOnDueDate" time="1195.007" classname="tests.QCStore"/>
  <testcase name="PaymentAndEod" time="91.797" classname="tests.QCStore">
    <error type="org.openqa.selenium.UnhandledAlertException" message="Modal dialog present: Please Select Product
Build info: version: &#039;3.14.0&#039;, revision: &#039;aacccce0&#039;, time: &#039;2018-08-02T20:19:58.91Z&#039;
System info: host: &#039;QTLSYS2-48&#039;, ip: &#039;192.168.2.48&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_171&#039;
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserAttachTimeout: 0, browserName: internet explorer, cssSelectorsEnabled: true, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, handlesAlerts: true, ie.browserCommandLineSwitches: , ie.ensureCleanSession: false, ie.forceCreateProcessApi: false, ie.usePerProcessProxy: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:34656/, javascriptEnabled: true, nativeEvents: true, platform: WINDOWS, platformName: WINDOWS, requireWindowFocus: false, takesScreenshot: true, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: 65697d82-dfdd-47b9-bc12-ede5e15cce8a
*** Element info: {Using=name, value=advanceRequestBean.paymentCollateralType}">
      <![CDATA[org.openqa.selenium.UnhandledAlertException: Modal dialog present: Please Select Product
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'QTLSYS2-48', ip: '192.168.2.48', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {browserAttachTimeout: 0, browserName: internet explorer, cssSelectorsEnabled: true, elementScrollBehavior: 0, enableElementCacheCleanup: true, enablePersistentHover: true, handlesAlerts: true, ie.browserCommandLineSwitches: , ie.ensureCleanSession: false, ie.forceCreateProcessApi: false, ie.usePerProcessProxy: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:34656/, javascriptEnabled: true, nativeEvents: true, platform: WINDOWS, platformName: WINDOWS, requireWindowFocus: false, takesScreenshot: true, unexpectedAlertBehaviour: dismiss, unhandledPromptBehavior: dismiss, version: 11}
Session ID: 65697d82-dfdd-47b9-bc12-ede5e15cce8a
*** Element info: {Using=name, value=advanceRequestBean.paymentCollateralType}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.createUnhandledAlertException(ErrorHandler.java:195)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:400)
at org.openqa.selenium.By$ByName.findElement(By.java:284)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
at tests.AQCCSRNewLoan.LOC(AQCCSRNewLoan.java:213)
at tests.AQCCSRNewLoan.newLoan(AQCCSRNewLoan.java:162)
at tests.QCStore.PaymentAndEod(QCStore.java:5571)
=======
<<<<<<< HEAD
<testsuite skipped="0" hostname="Ratikanta-pc" name="tests.QCStore" tests="14" failures="0" timestamp="05 Mar 2019 19:57:20 GMT" time="23917.266" errors="0">
  <testcase name="RQC_LOC_ManualDefault_Txn_Testdata" time="1054.945" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_Deposit_Return_ManualDefault_Txn_Testdata" time="1190.369" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_Deposit_Return_2ndDeposit_Clear_3rdDeposit_Return_Default_Txn_Testdata" time="3213.728" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_2missedPayment_Default_EOD_Txn_Testdata" time="1962.715" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_Default_DefaultPayment_Txn_Testdata" time="2091.489" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_Default_DefaultPayment_Void_Txn_Testdata" time="1975.016" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_Default_PartialDefaultPayment_Void_Txn_Testdata" time="1999.760" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_Default_DefaultPayment_Return_Txn_Testdata" time="2047.976" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_Default_PartialDefaultPayment_FullDefaultPayment_Txn_Testdata" time="1959.354" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_Default_PartialDefaultPayment_FullDefaultPayment_Void_Txn_Testdata" time="2009.703" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_PayOff_Closure_Txn_Testdata" time="561.404" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_Payment_PayOff_Closure_Void_Txn_Testdata" time="716.553" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_PayOff_Closure_PayoffReturn_Txn_Testdata" time="791.639" classname="tests.QCStore"/>
  <testcase name="RQC_LOC_PayOff_Agestore180days_AutoClosure_Txn_Testdata" time="2342.614" classname="tests.QCStore"/>
=======
<<<<<<< HEAD
<testsuite skipped="14" hostname="QTLSYS2-238" name="tests.QCStore" tests="16" failures="0" timestamp="04 Mar 2019 13:47:33 GMT" time="7298.303" errors="0">
  <testcase name="LOC_ACHDeposit_EOD_Return_EOD_Default_Redeposit_Txn" time="4660.096" classname="tests.QCStore"/>
  <testcase name="LOC_ACHDeposit_EOD_Return_EOD_Redeposit_Txn" time="2638.207" classname="tests.QCStore"/>
=======
<<<<<<< HEAD
<testsuite skipped="14" hostname="QTLSYS2-48" name="tests.QCStore" tests="16" failures="0" timestamp="01 Mar 2019 13:10:40 GMT" time="5.057" errors="2">
  <testcase name="getResult" time="5.034" classname="tests.QCStore">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at tests.QCStore.getScreenhot(QCStore.java:7091)
at tests.QCStore.getResult(QCStore.java:7107)
=======
<testsuite skipped="14" hostname="QTLSYS2-72pc" name="tests.QCStore" tests="28" failures="8" timestamp="05 Mar 2019 16:57:37 GMT" time="12283.983" errors="0">
  <testcase name="LOC_Payment_Return_PayOff_Txn" time="658.661" classname="tests.QCStore"/>
  <testcase name="LOC_PayOff_RescindPeriod_void_Txn" time="691.681" classname="tests.QCStore">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.QCVoid.qcVoid(QCVoid.java:177)
at tests.QCStore.LOC_PayOff_RescindPeriod_void_Txn(QCStore.java:817)
>>>>>>> jyothi1.1
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
<<<<<<< HEAD
    </error>
  </testcase> <!-- getResult -->
  <testcase name="EODOnDueDate" time="0.023" classname="tests.QCStore">
    <error type="java.io.FileNotFoundException" message="D:\QC_Batch\QC_LOC\TestData\QCStore\ALOC\QC_LOC_EODDuedate.xls (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: D:\QC_Batch\QC_LOC\TestData\QCStore\ALOC\QC_LOC_EODDuedate.xls (The system cannot find the path specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at tests.ExcelNew.<init>(ExcelNew.java:35)
at tests.QCStore.EODOnDueDate(QCStore.java:5634)
>>>>>>> 792c0d99c7dc98fb911ab128b442f178e0a75ffb
=======
    </failure>
  </testcase> <!-- LOC_PayOff_RescindPeriod_void_Txn -->
  <testcase name="LOC_Payment_PayOff_Void_Txn" time="1365.903" classname="tests.QCStore">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.QCVoid.qcVoid(QCVoid.java:177)
at tests.QCStore.LOC_Payment_PayOff_Void_Txn(QCStore.java:880)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LOC_Payment_PayOff_Void_Txn -->
  <testcase name="LOC_Payment_Gracedays_PayOff_Void_Txn" time="922.815" classname="tests.QCStore">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.QCVoid.qcVoid(QCVoid.java:177)
at tests.QCStore.LOC_Payment_Gracedays_PayOff_Void_Txn(QCStore.java:943)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LOC_Payment_Gracedays_PayOff_Void_Txn -->
  <testcase name="LOC_Payment_Void_PayOff_Void_Txn" time="820.504" classname="tests.QCStore">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.QCVoid.qcVoid(QCVoid.java:177)
at tests.QCStore.LOC_Payment_Void_PayOff_Void_Txn(QCStore.java:1007)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LOC_Payment_Void_PayOff_Void_Txn -->
  <testcase name="LOC_PayOff_Return_Txn" time="2209.821" classname="tests.QCStore">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.QCPayOff.payoff(QCPayOff.java:152)
at tests.QCStore.LOC_PayOff_Return_Txn(QCStore.java:1061)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LOC_PayOff_Return_Txn -->
  <testcase name="LOC_Payment_PayOff_Return_Txn" time="671.697" classname="tests.QCStore"/>
  <testcase name="LOC_Draw_Txn" time="421.122" classname="tests.QCStore"/>
  <testcase name="LOC_Payment_Draw_Txn" time="571.942" classname="tests.QCStore"/>
  <testcase name="LOC_PayOff_Draw_Txn" time="561.355" classname="tests.QCStore"/>
  <testcase name="LOC_Draw_Void_Txn" time="718.538" classname="tests.QCStore">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.QCVoid.qcVoid(QCVoid.java:177)
at tests.QCStore.LOC_Draw_Void_Txn(QCStore.java:1368)
>>>>>>> jyothi1.1
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
<<<<<<< HEAD
    </error>
<<<<<<< HEAD
  </testcase> <!-- PaymentAndEod -->
  <testcase name="VoidandEod" time="1368.741" classname="tests.QCStore"/>
  <testcase name="HigherPaymentAndEod" time="1337.773" classname="tests.QCStore"/>
  <testcase name="PayOFFandEod" time="1278.464" classname="tests.QCStore"/>
  <testcase name="DepositAndEOD" time="1221.698" classname="tests.QCStore"/>
  <testcase name="DrawAndEOD" time="1316.020" classname="tests.QCStore"/>
=======
  </testcase> <!-- EODOnDueDate -->
>>>>>>> 034e575dc96add0c75e87be5f99f7163fb9e1980
=======
    </failure>
  </testcase> <!-- LOC_Draw_Void_Txn -->
  <testcase name="LOC_Payment_Draw_Void_Txn" time="721.523" classname="tests.QCStore">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.QCVoid.qcVoid(QCVoid.java:177)
at tests.QCStore.LOC_Payment_Draw_Void_Txn(QCStore.java:1430)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LOC_Payment_Draw_Void_Txn -->
  <testcase name="LOC_PayOff_Draw_Void_Txn" time="751.458" classname="tests.QCStore">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.QCVoid.qcVoid(QCVoid.java:177)
at tests.QCStore.LOC_PayOff_Draw_Void_Txn(QCStore.java:1490)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LOC_PayOff_Draw_Void_Txn -->
  <testcase name="LOC_Deposit_Return_PayOff_Txn" time="1196.963" classname="tests.QCStore"/>
>>>>>>> jyothi1.1
  <testcase name="PayOFFandEod" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- PayOFFandEod -->
  <testcase name="PaymentdrawVoidEOD" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- PaymentdrawVoidEOD -->
  <testcase name="SignatureNewLoan_EODTwice" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- SignatureNewLoan_EODTwice -->
  <testcase name="DepositEODReDeposit" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- DepositEODReDeposit -->
  <testcase name="PaymentDepositEODReDeposit" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- PaymentDepositEODReDeposit -->
  <testcase name="Deposit_DrawEODTwice" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- Deposit_DrawEODTwice -->
  <testcase name="HigherPaymentAndEod" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- HigherPaymentAndEod -->
  <testcase name="VoidandEod" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- VoidandEod -->
  <testcase name="DepositEODTwice" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- DepositEODTwice -->
  <testcase name="PaymentAndEod" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- PaymentAndEod -->
<<<<<<< HEAD
  <testcase name="DepositAndEOD" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- DepositAndEOD -->
=======
  <testcase name="EODOnDueDate" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- EODOnDueDate -->
>>>>>>> jyothi1.1
  <testcase name="PaymentAndDraw" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- PaymentAndDraw -->
  <testcase name="DepositAndEOD" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- DepositAndEOD -->
  <testcase name="Clear_Return_EODTwice" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- Clear_Return_EODTwice -->
  <testcase name="DrawAndEOD" classname="tests.QCStore">
    <skipped/>
  </testcase> <!-- DrawAndEOD -->
<<<<<<< HEAD
=======
<testsuite skipped="0" hostname="Ratikanta-pc" name="tests.QCStore" tests="1" failures="0" timestamp="01 Mar 2019 11:59:31 GMT" time="1524.633" errors="0">
  <testcase name="JQC_LOC_Refinance_EOD_Payment_Txn" time="1524.633" classname="tests.QCStore"/>
>>>>>>> feb1.1
>>>>>>> cfd4415cf923aceeec44a0b1fca621dca6ccc529
>>>>>>> 792c0d99c7dc98fb911ab128b442f178e0a75ffb
=======
>>>>>>> jyothi1.1
</testsuite> <!-- tests.QCStore -->
